from __future__ import annotations

from ..core.i18n import pick_locale


ANSWER_MESSAGES = {
    "en": {
        "no_data": "No matching rows were found.",
        "no_data_detail": "No rows matched the current selection or post-processing rules.",
        "row_count_answer": "There are {value} rows in the active sheet.",
        "row_count_analysis": "A direct row count was executed on the current sheet.",
        "distinct_count_answer": "{column} has {value} distinct values.",
        "distinct_count_analysis": "The result counts unique values in {column}.",
        "active_day_count_answer": "{period} has data on {value} distinct days.",
        "active_day_count_analysis": "Filtered the sheet to {period} and counted distinct day buckets in {column}.",
        "total_amount_answer": "The total {column} is {value}.",
        "total_amount_analysis": "The result aggregates {column} across the current sheet.",
        "average_amount_answer": "The average {column} is {value}.",
        "average_amount_analysis": "The result computes the mean of {column} across the current sheet.",
        "what_if_reduction_answer": "Reducing {target} by {percent}% would lower the total by {reduction_value}.",
        "what_if_reduction_analysis": "Matched {target_column} = {target} and summed the current amount to {matched_value}; applying a {percent}% reduction gives {reduction_value}.",
        "ranking_answer": "{leader} ranks first at {leader_value}.",
        "ranking_analysis": "Among the top {limit} {dimension}, {leader} leads at {leader_value}{runner_clause}{chart_clause}",
        "ranking_top_list": "Top {limit}: {items}.",
        "ranking_risk_single_item": "Only one {dimension} item matched, so ranking contrast is limited.",
        "share_answer": "{leader} accounts for {leader_share} of the total.",
        "share_analysis": "{leader} has the largest share in {dimension} at {leader_share} ({leader_value}){runner_clause}{chart_clause}",
        "share_top_list": "Top {limit} shares: {items}.",
        "trend_answer": "{peak_period} is the peak for {metric} at {peak_value}.",
        "trend_analysis": "Across {point_count} periods, {metric} peaks in {peak_period} at {peak_value}; the latest point is {latest_period} at {latest_value}{change_clause}{chart_clause}",
        "trend_risk_short_series": "The trend is based on {point_count} periods only; treat direction changes as preliminary.",
        "period_breakdown_answer": "{items}.",
        "period_breakdown_analysis": "Grouped the source sheet by month and summed {metric}. {items}{chart_clause}",
        "forecast_answer": "The forecast for {period} is {value}.",
        "forecast_analysis": "Using {model} on {history_points} historical {grain} periods from {history_start} to {history_end}, the forecast for {period} is {value}.",
        "forecast_risk": "This is an estimate, not an exact calculation. The 95% reference interval is {lower} to {upper}.",
        "forecast_series_answer": "Forecasted {count} future {grain} periods from {start_period} to {end_period}.",
        "forecast_series_analysis": "Using {model} on {history_points} historical {grain} periods from {history_start} to {history_end}, generated {count} forecast points from {start_period} to {end_period}; total is {total_value}, average per {grain} is {average_value}.",
        "forecast_series_risk": "These are model estimates, not exact calculations. Each forecast row includes a 95% reference interval; the aggregated range is {lower} to {upper}.",
        "weekpart_compare_answer": "{leader_label} is higher at {leader_value}, versus {other_label} at {other_value}.",
        "weekpart_compare_analysis": "Grouped the date values into weekday versus weekend and summed {metric}. {leader_label}={leader_value}; {other_label}={other_value}{chart_clause}",
        "period_compare_answer": "Compared with {previous_period}, {current_period} is {current_value}, {direction} {change_value} ({change_pct}).",
        "period_compare_delta_answer": "Compared with {previous_period}, {current_period} is {current_value}, {direction} {change_value}.",
        "period_compare_ratio_answer": "{current_period} is {ratio_value} of {previous_period} ({current_value} vs {previous_value}).",
        "period_compare_analysis": "Kept the same scope and compared {metric} between {current_period} and {previous_period}. {previous_period}={previous_value}; {current_period}={current_value}.",
        "period_compare_risk_zero_base": "The base period {previous_period} is 0, so ratio and percentage interpretation is limited.",
        "explain_breakdown_answer": "Within {target}, {leader} contributes the most in {dimension} at {leader_value}.",
        "explain_breakdown_analysis": "Kept {target_dimension} = {target} and regrouped by {dimension}. {leader} ranks first at {leader_value}{runner_clause}.",
        "detail_answer": "Returned {count} detail rows sorted by {column}.",
        "detail_analysis": "Showing {count} detail rows sorted by {column}. First row: {row_summary}.",
        "explain_item_answer": "{target} is an item from the previous result. Returned {count} matching rows to explain it.",
        "explain_item_analysis": "Filtered the source sheet where {dimension} = {target} and returned {count} rows. {summary_sentence} First row: {row_summary}.",
        "ranked_item_answer": "The {rank_position} item is {target} at {target_value}.",
        "ranked_item_analysis": "Looked up the {rank_position} item in the previous ranking for {dimension}.",
        "pivot_answer": "Returned {row_count} pivoted rows and {value_column_count} value columns.",
        "pivot_analysis": "Pivoted {value_label} by {pivot_column} for {index_label}. First row: {row_summary}.",
        "table_answer": "Returned {row_count} rows and {column_count} columns.",
        "table_analysis": "Result columns: {columns}. First row: {row_summary}.",
        "table_analysis_no_row": "Result columns: {columns}.",
        "runner_clause": "; runner-up is {runner} at {runner_value}",
        "runner_share_clause": "; runner-up is {runner} at {runner_share} ({runner_value})",
        "trend_change_up": ", up {delta_value} from the first point",
        "trend_change_down": ", down {delta_value} from the first point",
        "trend_change_flat": ", unchanged from the first point",
        "chart_clause": ". A {chart_type} chart was generated.",
        "chart_type_bar": "bar",
        "chart_type_line": "line",
        "chart_type_pie": "pie",
        "chart_type_scatter": "scatter",
    },
    "zh-CN": {
        "no_data": "没有找到符合条件的数据行。",
        "no_data_detail": "当前筛选或后处理规则下没有匹配结果。",
        "row_count_answer": "当前工作表共有 {value} 行。",
        "row_count_analysis": "本次结果来自对当前工作表的直接计数。",
        "distinct_count_answer": "{column} 去重后共有 {value} 个值。",
        "distinct_count_analysis": "结果统计了 {column} 的唯一值数量。",
        "active_day_count_answer": "{period} 共有 {value} 天有数据。",
        "active_day_count_analysis": "已筛选 {period}，并按 {column} 去重统计实际有数据的日期数。",
        "total_amount_answer": "{column} 总计为 {value}。",
        "total_amount_analysis": "结果对当前工作表中的 {column} 做了汇总求和。",
        "average_amount_answer": "{column} 平均值为 {value}。",
        "average_amount_analysis": "结果计算了当前工作表中 {column} 的平均值。",
        "what_if_reduction_answer": "如果将 {target} 的费用降低 {percent}%，总金额会减少 {reduction_value}。",
        "what_if_reduction_analysis": "已按 {target_column} = {target} 筛出当前金额 {matched_value}；按降低 {percent}% 计算，减少额为 {reduction_value}。",
        "ranking_answer": "{leader} 目前排在第 1，数值为 {leader_value}。",
        "ranking_analysis": "在前 {limit} 个{dimension}结果中，{leader} 以 {leader_value} 排名第一{runner_clause}{chart_clause}",
        "ranking_top_list": "前 {limit} 项分别为：{items}。",
        "ranking_risk_single_item": "当前仅命中 1 个{dimension}项，排名对比样本有限。",
        "share_answer": "{leader} 占总量的 {leader_share}。",
        "share_analysis": "{dimension} 中占比最高的是 {leader}，占比 {leader_share}，对应数值 {leader_value}{runner_clause}{chart_clause}",
        "share_top_list": "前 {limit} 项占比分别为：{items}。",
        "trend_answer": "{metric} 的峰值出现在 {peak_period}，数值为 {peak_value}。",
        "trend_analysis": "共覆盖 {point_count} 个周期，{metric} 在 {peak_period} 达到峰值 {peak_value}；最新一期 {latest_period} 为 {latest_value}{change_clause}{chart_clause}",
        "trend_risk_short_series": "当前趋势仅基于 {point_count} 个周期，方向判断建议结合更多历史数据复核。",
        "period_breakdown_answer": "{items}。",
        "period_breakdown_analysis": "已按月份对 {metric} 做汇总。{items}{chart_clause}",
        "forecast_answer": "预测 {period} 的总费用约为 {value}。",
        "forecast_analysis": "基于 {history_start} 到 {history_end} 的 {history_points} 个{grain}历史周期，使用 {model} 得出 {period} 的预测值为 {value}。",
        "forecast_risk": "该结果为模型估计，不是精确计算。95% 参考区间约为 {lower} 到 {upper}。",
        "forecast_series_answer": "已预测 {start_period} 到 {end_period} 共 {count} 个未来{grain}周期的费用。",
        "forecast_series_analysis": "基于 {history_start} 到 {history_end} 的 {history_points} 个{grain}历史周期，使用 {model} 生成了 {start_period} 到 {end_period} 共 {count} 个预测点；预测总计约为 {total_value}，平均每{grain}约为 {average_value}。",
        "forecast_series_risk": "这些结果为模型估计，不是精确计算。结果表格中每个预测点都带有 95% 参考区间；聚合参考区间约为 {lower} 到 {upper}。",
        "weekpart_compare_answer": "{leader_label}消费更高，为 {leader_value}；{other_label} 为 {other_value}。",
        "weekpart_compare_analysis": "已将日期归并为工作日与周末，并对 {metric} 求和。{leader_label}={leader_value}；{other_label}={other_value}{chart_clause}",
        "period_compare_answer": "与 {previous_period} 相比，{current_period} 为 {current_value}，{direction}{change_value}（{change_pct}）。",
        "period_compare_delta_answer": "与 {previous_period} 相比，{current_period} 为 {current_value}，{direction}{change_value}。",
        "period_compare_ratio_answer": "{current_period} 相当于 {previous_period} 的 {ratio_value}（{current_value} vs {previous_value}）。",
        "period_compare_analysis": "已保持相同筛选口径，对 {metric} 在 {previous_period} 与 {current_period} 之间做精确对比。{previous_period}={previous_value}；{current_period}={current_value}。",
        "period_compare_risk_zero_base": "基准周期 {previous_period} 为 0，倍数与变化率口径仅供参考。",
        "explain_breakdown_answer": "在 {target} 内，{dimension} 里贡献最高的是 {leader}，数值为 {leader_value}。",
        "explain_breakdown_analysis": "已保持 {target_dimension} = {target} 的筛选条件，并改为按 {dimension} 重新汇总。{leader} 排名第一，数值为 {leader_value}{runner_clause}。",
        "detail_answer": "已返回按 {column} 排序的 {count} 条明细。",
        "detail_analysis": "当前展示按 {column} 排序的 {count} 条明细。首行示例：{row_summary}。",
        "explain_item_answer": "{target} 是上一轮结果里的项目，已返回 {count} 条相关明细帮助解释。",
        "explain_item_analysis": "已按 {dimension} = {target} 回到原表筛出 {count} 条记录。{summary_sentence} 首行示例：{row_summary}。",
        "ranked_item_answer": "{rank_position}是 {target}，数值为 {target_value}。",
        "ranked_item_analysis": "已沿用上一轮排行结果，定位到 {dimension} 的{rank_position}。",
        "pivot_answer": "已返回 {row_count} 条透视结果，包含 {value_column_count} 个数值列。",
        "pivot_analysis": "结果按 {pivot_column} 对 {value_label} 做透视，行维度为 {index_label}。首行示例：{row_summary}。",
        "table_answer": "已返回 {row_count} 行、{column_count} 列结果。",
        "table_analysis": "结果列包括：{columns}。首行示例：{row_summary}。",
        "table_analysis_no_row": "结果列包括：{columns}。",
        "runner_clause": "；第二名是 {runner}，数值为 {runner_value}",
        "runner_share_clause": "；第二名是 {runner}，占比 {runner_share}，数值为 {runner_value}",
        "trend_change_up": "，较首期上升 {delta_value}",
        "trend_change_down": "，较首期下降 {delta_value}",
        "trend_change_flat": "，与首期持平",
        "chart_clause": "。已生成 {chart_type} 图表。",
        "chart_type_bar": "柱状",
        "chart_type_line": "折线",
        "chart_type_pie": "饼",
        "chart_type_scatter": "散点",
    },
    "ja-JP": {
        "no_data": "一致する行は見つかりませんでした。",
        "no_data_detail": "現在の選択条件または後処理条件に一致する結果はありません。",
        "row_count_answer": "アクティブシートには {value} 行あります。",
        "row_count_analysis": "現在のシートに対して直接件数集計を実行しました。",
        "distinct_count_answer": "{column} の重複除外件数は {value} です。",
        "distinct_count_analysis": "結果は {column} のユニーク値件数を集計しています。",
        "active_day_count_answer": "{period} にデータがある日は {value} 日です。",
        "active_day_count_analysis": "{period} に絞り込み、{column} を日単位で重複除外集計しました。",
        "total_amount_answer": "{column} の合計は {value} です。",
        "total_amount_analysis": "結果は現在のシート全体で {column} を合計しています。",
        "average_amount_answer": "{column} の平均は {value} です。",
        "average_amount_analysis": "結果は現在のシート全体で {column} の平均を計算しています。",
        "what_if_reduction_answer": "{target} の費用を {percent}% 下げると、合計は {reduction_value} 減ります。",
        "what_if_reduction_analysis": "{target_column} = {target} に一致する現在金額は {matched_value} で、{percent}% 引き下げると減少額は {reduction_value} です。",
        "ranking_answer": "{leader} が {leader_value} で 1 位です。",
        "ranking_analysis": "上位 {limit} 件の {dimension} の中では、{leader} が {leader_value} で首位です{runner_clause}{chart_clause}",
        "ranking_top_list": "上位 {limit} 件: {items}。",
        "ranking_risk_single_item": "{dimension} で一致した項目が 1 件のみのため、ランキング比較の解像度は限定的です。",
        "share_answer": "{leader} が全体の {leader_share} を占めています。",
        "share_analysis": "{dimension} の中では {leader} が最大シェアで、{leader_share} ({leader_value}) です{runner_clause}{chart_clause}",
        "share_top_list": "上位 {limit} 件のシェア: {items}。",
        "trend_answer": "{metric} のピークは {peak_period} の {peak_value} です。",
        "trend_analysis": "{point_count} 期間を見ると、{metric} は {peak_period} に {peak_value} でピークとなり、最新の {latest_period} は {latest_value} です{change_clause}{chart_clause}",
        "trend_risk_short_series": "このトレンドは {point_count} 期間のみを基にしており、方向判断は暫定的です。",
        "period_breakdown_answer": "{items}。",
        "period_breakdown_analysis": "{metric} を月別に集計しました。{items}{chart_clause}",
        "forecast_answer": "{period} の合計費用予測は {value} です。",
        "forecast_analysis": "{history_start} から {history_end} までの {history_points} 個の {grain} 履歴期間に対して {model} を適用し、{period} を {value} と予測しました。",
        "forecast_risk": "これは推定値であり、厳密計算ではありません。95% の参考区間は {lower} から {upper} です。",
        "forecast_series_answer": "{start_period} から {end_period} までの将来 {count} 個の {grain} 期間を予測しました。",
        "forecast_series_analysis": "{history_start} から {history_end} までの {history_points} 個の {grain} 履歴期間に対して {model} を適用し、{start_period} から {end_period} まで {count} 個の予測点を生成しました。予測合計は {total_value}、1 {grain} あたり平均は {average_value} です。",
        "forecast_series_risk": "これらはモデル推定であり、厳密計算ではありません。結果テーブルの各予測点に 95% の参考区間があり、集計参考区間は {lower} から {upper} です。",
        "weekpart_compare_answer": "{leader_label} の方が高く、{leader_value} です。{other_label} は {other_value} です。",
        "weekpart_compare_analysis": "日付を平日と週末にまとめて {metric} を合計しました。{leader_label}={leader_value}、{other_label}={other_value}{chart_clause}",
        "period_compare_answer": "{previous_period} と比べると、{current_period} は {current_value} で、{direction} {change_value} ({change_pct}) です。",
        "period_compare_delta_answer": "{previous_period} と比べると、{current_period} は {current_value} で、{direction} {change_value} です。",
        "period_compare_ratio_answer": "{current_period} は {previous_period} の {ratio_value} です（{current_value} vs {previous_value}）。",
        "period_compare_analysis": "同じ条件を保ったまま、{metric} を {previous_period} と {current_period} で比較しました。{previous_period}={previous_value}、{current_period}={current_value}。",
        "period_compare_risk_zero_base": "基準期間 {previous_period} が 0 のため、比率・増減率の解釈には制約があります。",
        "explain_breakdown_answer": "{target} の中では、{dimension} の {leader} が {leader_value} で最大です。",
        "explain_breakdown_analysis": "{target_dimension} = {target} を維持したまま、{dimension} で再集計しました。{leader} が {leader_value} で首位です{runner_clause}。",
        "detail_answer": "{column} で並べ替えた詳細行を {count} 件返しました。",
        "detail_analysis": "{column} で並べ替えた詳細行を {count} 件表示しています。先頭行: {row_summary}。",
        "explain_item_answer": "{target} は前回結果に出ていた項目です。説明のため一致する {count} 行を返しました。",
        "explain_item_analysis": "{dimension} = {target} で元シートを絞り込み、{count} 行を返しました。{summary_sentence} 先頭行: {row_summary}。",
        "ranked_item_answer": "{dimension} の {rank_position} は {target} で、値は {target_value} です。",
        "ranked_item_analysis": "前回のランキング結果から {dimension} の {rank_position} を特定しました。",
        "pivot_answer": "ピボット結果を {row_count} 行返し、値列は {value_column_count} 列です。",
        "pivot_analysis": "{index_label} ごとに {pivot_column} で {value_label} をピボットしました。先頭行: {row_summary}。",
        "table_answer": "{row_count} 行 {column_count} 列の結果を返しました。",
        "table_analysis": "結果列: {columns}。先頭行: {row_summary}。",
        "table_analysis_no_row": "結果列: {columns}。",
        "runner_clause": "、2 位は {runner} の {runner_value} です",
        "runner_share_clause": "、2 位は {runner} で {runner_share} ({runner_value}) です",
        "trend_change_up": "、初回より {delta_value} 増加",
        "trend_change_down": "、初回より {delta_value} 減少",
        "trend_change_flat": "、初回から横ばい",
        "chart_clause": "。{chart_type} チャートを生成しました。",
        "chart_type_bar": "棒",
        "chart_type_line": "折れ線",
        "chart_type_pie": "円",
        "chart_type_scatter": "散布",
    },
}


def _ta(locale: str, key: str, **kwargs: object) -> str:
    template = ANSWER_MESSAGES[pick_locale(locale)][key]
    return template.format(**kwargs)
